name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  cd-deploy-prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel

      - name: Configure Databricks
        run: |
          # write out the profile (here called "TEST")
          cat <<EOF > ~/.databrickscfg
          [TEST]
          host      = https://dbc-f258a182-511d.cloud.databricks.com/
          auth_type = databricks-cli
          EOF

      - name: Deploy to PROD
        run: |
          databricks bundle validation \
            --target prod

      - name: Deploy to PROD
        run: |
          databricks bundle deploy \
            --target prod 
